### PR TITLE
Migrate to jest

### PR DESCRIPTION
**Pull request by sibiraj-s**
Migrate to jest

### CODE REVIEW

**Review by rexxars — CHANGES_REQUESTED** [review]
Can we move the jest config to `package.json` (and get rid of anything but the required config)?

**Comment by sibiraj-s** [comment]
> Can we move the jest config to `package.json` (and get rid of anything but the required config)?

No preference there. package.json is fine for me. but Considering the number of options in the jest config, manifest file can get little clumsy. And when typescript comes we will need to add few more configs. may be some regexes. js file will flexible to work with. I think. thoughts?

I can remove the unwanted options and comments though?

**Comment by sibiraj-s** [comment]
Dang it. Let's worry about the readability issue when there is one 😅 . Moved to package.json

**Review by rexxars — APPROVED** [review]
Great - thanks for doing this!

**Pull request merged**
