### PR TITLE
feat: drop use of prop-types

### PR DESCRIPTION
**Pull request by rexxars**
As discussed in #9 - lets drop the use of proptypes. We can introduce typescript soonish.

### CODE REVIEW

**Review by sibiraj-s — APPROVED** [review]
LGTM 🚀

**Comment by sibiraj-s** [comment]
Typescript switch before or after the release?

**Comment by rexxars** [comment]
Shouldn't be a breaking change to introduce typescript, so I'd say after?

**Comment by sibiraj-s** [comment]
> Shouldn't be a breaking change to introduce typescript, so I'd say after?

Yeah. there won't be any breaking changes. After is fine. So it won't delay the release. hightlight has some vulnerabilities with the supported version at the moment.

**Comment by sibiraj-s** [comment]
Can you configure github pages to use `gh-pages` branch. seems to be serving the cached version

**Comment by rexxars** [comment]
Yup, done.

**Pull request merged**
