### PR TITLE
Lowlight v2 + ESM

### LINKED ISSUE #5: Register all languages from highlight.js
I am creating a project that renders markdown files from multiple repositories in Github. So I don't know exactly what was render, that can be code snippets in different languages. Is there a way to register all languages from highlight.js? My actual code looks like this:

```js
import React from "react";
import Lowlight from "react-lowlight";
import "highlight.js/styles/srcery.css";

import bash from "highlight.js/lib/languages/bash";
import cLike from "highlight.js/lib/languages/c-like";
import elixir from "highlight.js/lib/languages/elixir";
import html from "highlight.js/lib/languages/htmlbars";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import markdown from "highlight.js/lib/languages/markdown";
import php from "highlight.js/lib/languages/php";
import python from "highlight.js/lib/languages/python";
import ruby from "highlight.js/lib/languages/ruby";

Lowlight.registerLanguage("bash", bash);
Lowlight.registerLanguage("c", cLike);
Lowlight.registerLanguage("cpp", cLike);
Lowlight.registerLanguage("csharp", cLike);
Lowlight.registerLanguage("elixir", elixir);
Lowlight.registerLanguage("html", html);
Lowlight.registerLanguage("java", java);
Lowlight.registerLanguage("js", javascript);
Lowlight.registerLanguage("md", markdown);
Lowlight.registerLanguage("php", php);
Lowlight.registerLanguage("py", python);
Lowlight.registerLanguage("ruby", ruby);

let langs = ["bash", "c", "cpp", "cs", "elixir", "html", "java", "js", "md", "php", "py", "ruby"];

function CodeRenderer(props) {
  const { language, ...rest } = props;
  const found = langs.find((lang) => lang === language);

  return <Lowlight language={found ? language : undefined} {...rest} />;
}

export default CodeRenderer;
```

### LINKED ISSUE #8: Update to lowlight 2 and fix vulnerabilities
- Update to lowlight v2. 
- Update to highlight.js v11 (current dependent version has some vulnerabilities)

### PR DESCRIPTION
**Pull request by sibiraj-s**
- update to lowlight v2
- requires hightlightjs v11
- replace istanbul with nyc
- switch to ESM
- migrate from travis to github actions
- re-exports `lowlight/lib/{common/all}.js`

Fixes #8, Closes #5

### CODE REVIEW

**Comment by sibiraj-s** [comment]
There are still changes like,

- [x] demo is compiler based need to configure deployment to github pages.
- [ ] may be migrate to jest?
- [x] and some cleanup

~I can do it in another PR?~

**Comment by sibiraj-s** [comment]
Ping @rexxars

**Comment by sibiraj-s** [comment]
@rexxars can we merge this?

**Comment by rexxars** [comment]
Sorry, I need a little more time before I can review - work and real life got me stretched. Promise I'll have a look next week!

**Comment by sibiraj-s** [comment]
Sure. Thank you 👍

**Comment by sibiraj-s** [comment]
Let me know If you need any help to maintain this lib. Happy to help out.

**Comment by rexxars** [comment]
Hey Sibiraj, sorry for the late follow up, and thanks for all the awesome work you put into this!

Would love to have you help out as a maintainer for sure.

Some questions on the PR:
- Looks like there is no build step, so this will only work with browsers that support the features used (arrow functions, let/const etc). Are we okay with that? I had a bit of a hard time figuring out what the browser support of lowlight and highlight.js actually _is_ these days
- Given that this is a major version bump, I'd like to remove the usage of prop-types. I'd love to rewrite this library to use typescript in the near future when I get my head above water, and prop-types just seems like it's out of fashion these days. Agree? Disagree?

Aside from that, this is all a big thumbs up from me. Great work, thanks for taking the time and digging into this!

**Comment by sibiraj-s** [comment]
> Would love to have you help out as a maintainer for sure.

Awesome. 😄 

> Looks like there is no build step, so this will only work with browsers that support the features used (arrow functions, let/const etc). Are we okay with that? 

True. Only IE was the old browser I thought of. I do forgot about other older versions of other browsers 😅 when I removed the build step. We can do few things here. 

Option 1: Since most of the users already use bundlers. They can configure their tool to include `react-lowlight` from excluded for transpilation. An example with webpack+babel

```js
{
 test: /\.js(x)?$/,
 exclude: /node_modules\/(?!react-lowlight)/,
 use: 'babel-loader'
}
```

We can put this in README.

Tools like vite autodetects esm and compiles it without any extra step.

Option 2: We can setup a simple build step and use babel to transpile few syntaxes we use. Babel by default supporst most of the stage3 proposals. A simple `Rollup + babel` setup would suffice.

> Given that this is a major version bump, I'd like to remove the usage of prop-types. I'd love to rewrite this library to use typescript in the near future when I get my head above water, and prop-types just seems like it's out of fashion these days. Agree? Disagree?

Agreed. I don't use proptypes at all, I have almost forgotten about it. Definitely we can move to typescript. Editors are now smart enough show errors/warnings upfront with typings.

Migrating to typescript can also fix the above mentioned problem as well. Build step with rollup can be skipped and typescript compiler would be enough for our usecase I think.

But I would like to deal with typescript in another PR. Is that fine?

**Comment by sibiraj-s** [comment]
On a second thought about browser support. I am not sure how bundlers handle ESM alone packages. May be they compile it by default with whatever user configured for their app🤔. I can check about this. Anyhow since lowlight is pure ESM. Along with `react-lowlight` they might need to configure for  bundlers to include `lowlight` as well for compilation.

Checking lowlights compiled output, it has arrow functions left as is.

**Comment by rexxars** [comment]
You're right - it seems lowlight does indeed ship with ESM only and no compilation of arrow functions and such. With that in mind, I think it is fine to do the same for this library - we can work on migrating to typescript in a separate flow.

**Comment by rexxars** [comment]
I've released [3.0.0-alpha.0](https://www.npmjs.com/package/react-lowlight/v/3.0.0-alpha.0) on npm with all these changes - give it a go and let me know if it works as expected, yeah?

**Comment by sibiraj-s** [comment]
Sure.

**Comment by sibiraj-s** [comment]
Tested the recent changes with vite. Works flawlessly as expected. It should work fine on other bundlers as well.

We needed these changes for our app as well with usage in [marked-react](https://github.com/sibiraj-s/marked-react). It works fine with that package as well.

Thanks @rexxars. 🚀 .

**Comment by sibiraj-s** [comment]
New changes like.
- forward ref
- new path `react-lowlight/all` 

works fine as well.

**Comment by rexxars** [comment]
Great. Releasing v3.0.0 now 🎉

**Pull request merged**
